// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenRemote_Sender_Ui

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OpenRemote = lv_label_create(ui_Home);
    lv_obj_set_width(ui_OpenRemote, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OpenRemote, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OpenRemote, 5);
    lv_obj_set_y(ui_OpenRemote, 5);
    lv_label_set_text(ui_OpenRemote, "OpenRemote");
    lv_obj_set_style_text_color(ui_OpenRemote, lv_color_hex(0x4CB709), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OpenRemote, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
