// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRemote_Sender_Ui

#ifndef _OPENREMOTE_SENDER_UI_UI_H
#define _OPENREMOTE_SENDER_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
void ui_event_MenuButton(lv_event_t * e);
extern lv_obj_t * ui_MenuButton;
// SCREEN: ui_Menu
void ui_Menu_screen_init(void);
extern lv_obj_t * ui_Menu;
void ui_event_ExitButton(lv_event_t * e);
extern lv_obj_t * ui_ExitButton;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_ExitLabel;
extern lv_obj_t * ui_MenuLabel;
extern lv_obj_t * ui_ServoButton;
extern lv_obj_t * ui_ServoLabel;
extern lv_obj_t * ui_ModelButton;
extern lv_obj_t * ui_ModelLabel;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_PageUpButton;
extern lv_obj_t * ui_PageDownButton;
extern lv_obj_t * ui_UpLabel;
extern lv_obj_t * ui_DownLabel;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
