// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenRemote_Sender_Ui

#ifndef _UI_COMP_OPENREMOTE_H
#define _UI_COMP_OPENREMOTE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT OpenRemote
#define UI_COMP_OPENREMOTE_OPENREMOTE 0
#define _UI_COMP_OPENREMOTE_NUM 1
lv_obj_t * ui_OpenRemote_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
