// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: OpenRemote_Sender_Ui

#include "../ui.h"


// COMPONENT OpenRemote

lv_obj_t * ui_OpenRemote_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_OpenRemote;
    cui_OpenRemote = lv_label_create(comp_parent);
    lv_obj_set_width(cui_OpenRemote, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_OpenRemote, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_OpenRemote, 5);
    lv_obj_set_y(cui_OpenRemote, 5);
    lv_label_set_text(cui_OpenRemote, "OpenRemote");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_OPENREMOTE_NUM);
    children[UI_COMP_OPENREMOTE_OPENREMOTE] = cui_OpenRemote;
    lv_obj_add_event_cb(cui_OpenRemote, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_OpenRemote, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_OpenRemote_create_hook(cui_OpenRemote);
    return cui_OpenRemote;
}

