// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: OpenRemote_Sender_Ui

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuButton = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_MenuButton, 36);
    lv_obj_set_height(ui_MenuButton, 36);
    lv_obj_set_x(ui_MenuButton, 2);
    lv_obj_set_y(ui_MenuButton, 2);
    lv_obj_add_flag(ui_MenuButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_MenuButton, ui_event_MenuButton, LV_EVENT_ALL, NULL);

}
